In [1]:
## numpy and scipy used to perform basic scientific programming operation

In [4]:
# numpy
    #1. array
    #2. matrices
    #3. linear algebra
    #4. random number generation
    #5. broadcasting
# scipy
    #1. integration
    #2. differential equation solver
    #3. statistics etc

In [3]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [6]:
## array - collection of elements of same data type

In [7]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [ ]:
#np.array

In [8]:
a=np.array([1,2,3,4])

In [9]:
a

array([1, 2, 3, 4])

In [10]:
a=np.array([[1,2],[3,4]])

In [11]:
a

array([[1, 2],
       [3, 4]])

In [12]:
a=np.array([1,2,3,4], dtype='f')

In [13]:
a

array([1., 2., 3., 4.], dtype=float32)

In [14]:
a=np.array([1,2,3,4], dtype='complex')

In [15]:
a

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [16]:
## np.arange

In [17]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [18]:
a=np.arange(1,10)

In [19]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a=np.arange(3)

In [21]:
a

array([0, 1, 2])

In [22]:
a=np.arange(1,10,2)

In [23]:
a

array([1, 3, 5, 7, 9])

In [24]:
a=np.arange(0.1, 1., 2.)

In [25]:
a

array([0.1])

In [26]:
a=np.arange(10,dtype='complex')

In [27]:
a

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

In [31]:
a=np.arange(0,1., 0.02, dtype='float')

In [32]:
a

array([0.  , 0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 ,
       0.22, 0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42,
       0.44, 0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64,
       0.66, 0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86,
       0.88, 0.9 , 0.92, 0.94, 0.96, 0.98])

In [33]:
# np.zeros

In [34]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [35]:
a=np.zeros(10)

In [36]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
a=np.zeros(10, dtype='int')

In [40]:
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
a=np.zeros((2,2))

In [42]:
a

array([[0., 0.],
       [0., 0.]])

In [44]:
a=np.zeros([4,4], dtype='int')

In [45]:
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [46]:
a=np.zeros([4,4], dtype='int', order='C')

In [47]:
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [48]:
# np.ones

In [50]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. note::
            

In [51]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
np.ones(7, dtype='int')

array([1, 1, 1, 1, 1, 1, 1])

In [53]:
np.ones((2,3), dtype='int')

array([[1, 1, 1],
       [1, 1, 1]])

In [54]:
# np.empty

In [55]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this 

In [56]:
np.empty(5)

array([6.01347002e-154, 7.65733063e-096, 1.95360624e-109, 7.04142211e-009,
       2.80321077e-085])

In [57]:
np.empty((3,4), dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [58]:
#np.linspace

In [59]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [65]:
np.linspace(2., 3., 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [66]:
np.linspace(1,100, num=5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [67]:
np.linspace(1, 100, num=5, endpoint=False)

array([ 1. , 20.8, 40.6, 60.4, 80.2])

In [69]:
np.linspace(1, 100, num=5, retstep=True)

(array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ]), 24.75)

In [70]:
np.linspace(1,100, num=5, dtype='int')

array([  1,  25,  50,  75, 100])

In [71]:
# eye()

In [72]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_functi

In [73]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [74]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [76]:
np.eye(3,5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [77]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [78]:
np.eye(5, k=2, dtype='int')

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [79]:
np.eye(5, k=-1, dtype='int')

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [81]:
np.eye(5,6, k=2, dtype='int')

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0]])

In [82]:
#np.identity

In [83]:
help(np.identity)

Help on function identity in module numpy:

identity(n, dtype=None, *, like=None)
    Return the identity array.
    
    The identity array is a square array with ones on
    the main diagonal.
    
    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. note::
            The ``like`` keyword is an experimental feature pending on
            acceptance of :ref:`NEP 35 <NEP35>`.
    
        .. versionadded:: 1.20.0
    
    Returns
    -------
    out : ndarray
        `n` x `n` 

In [84]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [85]:
np.identity(4, dtype='int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [87]:
# random()
    #rand()
    #randn()
    #ranf()
    #randint()

In [88]:
help(np.random)

Help on package numpy.random in numpy:

NAME
    numpy.random

DESCRIPTION
    Random Number Generation
    
    Use ``default_rng()`` to create a `Generator` and call its methods.
    
    =============== =========================================================
    Generator
    --------------- ---------------------------------------------------------
    Generator       Class implementing all of the random number distributions
    default_rng     Default constructor for ``Generator``
    =============== =========================================================
    
    ============================================= ===
    BitGenerator Streams that work with Generator
    --------------------------------------------- ---
    MT19937
    PCG64
    Philox
    SFC64
    ============================================= ===
    
    ============================================= ===
    Getting entropy to initialize a BitGenerator
    --------------------------------------------- ---
    Seed

In [89]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [90]:
np.random.rand(5)

array([0.31655222, 0.91913237, 0.31390792, 0.16296065, 0.77855035])

In [91]:
np.random.rand(5,3)

array([[0.55128178, 0.02432633, 0.63283826],
       [0.74332351, 0.06278154, 0.6885953 ],
       [0.47307835, 0.11149145, 0.32164396],
       [0.14533034, 0.10006015, 0.02578773],
       [0.70348829, 0.62916633, 0.46631889]])

In [93]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    .. note::
        New code should use the ``standard_normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned if no argument is provided.
 

In [94]:
np.random.randn()

0.6202588412210659

In [95]:
np.random.randn(5)

array([ 0.88930252,  0.83578344,  1.32784221, -1.00711043, -0.61217877])

In [99]:
help(np.random.ranf)

Help on built-in function ranf in module numpy.random.mtrand:

ranf(...)
    This is an alias of `random_sample`. See `random_sample`  for the complete
    documentation.



In [100]:
np.random.random_sample()

0.5024523143315313

In [101]:
np.random.random_sample(5)

array([0.76326333, 0.02040865, 0.0254358 , 0.94208599, 0.35553268])

In [106]:
5*np.random.random_sample((3,2)) -5

array([[-1.48879504, -0.59454493],
       [-0.23361378, -2.09003947],
       [-3.0954387 , -3.55027186]])

In [107]:
#np.random.randint

In [108]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [109]:
np.random.randint(2)

0

In [110]:
np.random.randint(2, size=5)

array([1, 0, 1, 0, 0])

In [112]:
np.random.randint(5, size=(4, 3))

array([[4, 0, 3],
       [3, 2, 1],
       [1, 1, 4],
       [2, 4, 0]])

In [113]:
#lower bound
np.random.randint(1, [3, 5, 10])

array([2, 1, 6])

In [114]:
#upper bound
np.random.randint([1, 5, 7], 10)

array([4, 9, 9])

In [115]:
#broadcasting
np.random.randint([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)

array([[ 7,  9,  7,  7],
       [ 7, 10,  6, 11]], dtype=uint8)

In [2]:
## atributes

In [3]:
# ndim

In [4]:
a=np.array([2,3,4,5])
a.ndim

1

In [5]:
a=np.array([[2,3,4],[4,5,6]])
a.ndim

2

In [6]:
#shape

In [7]:
a=np.array([2,3,4,5])
a.shape

(4,)

In [8]:
a=np.array([[2,3,4],[4,5,6]])
a.shape

(2, 3)

In [9]:
a=np.array([[[2,3],[3,4],[5,6]]])
a.shape

(1, 3, 2)

In [11]:
#shape

In [12]:
a=np.array([2,3,4,5])
a.size

4

In [13]:
a=np.array([[2,3,4],[4,5,6]])
a.size

6

In [14]:
a=np.array([[[2,3],[3,4],[5,6]]])
a.size

6

In [15]:
#dtype

In [18]:
a.dtype

dtype('int32')

In [19]:
#itemsize-- each item size in array

In [20]:
a.itemsize

4

In [21]:
## Data Types

In [22]:
# numerical data type

In [23]:
#1. bool, 2. int 3. float 4.complex

In [24]:
a=np.zeros(5)

In [25]:
a.dtype

dtype('float64')

In [26]:
b=np.zeros(6, dtype=np.int8)

In [27]:
b

array([0, 0, 0, 0, 0, 0], dtype=int8)

In [28]:
b=np.zeros(6, dtype=int)

In [29]:
b

array([0, 0, 0, 0, 0, 0])

In [30]:
x=np.float32(1)

In [31]:
x

1.0

In [33]:
x.dtype

dtype('float32')

In [34]:
x=np.array([2,3],dtype='f')

In [35]:
x

array([2., 3.], dtype=float32)

In [36]:
x=np.zeros(3)

In [37]:
x

array([0., 0., 0.])

In [38]:
x.astype(int)

array([0, 0, 0])

In [39]:
np.float64(x)

array([0., 0., 0.])

In [40]:
## indexing -- retrive single value

In [41]:
a=np.array([2,4,5,6,7])

In [42]:
a[3]

6

In [43]:
a[-3]

5

In [44]:
a=np.array([[2,3,4],[4,5,6]])
a

array([[2, 3, 4],
       [4, 5, 6]])

In [47]:
a[1,2]

6

In [52]:
a[1][2]

6

In [53]:
a[-1,-1]

6

In [54]:
a[1]

array([4, 5, 6])

In [57]:
a=np.array([[[1,2,3],[2,4,5],[4,5,6]]])

In [58]:
a

array([[[1, 2, 3],
        [2, 4, 5],
        [4, 5, 6]]])

In [59]:
a[0,1,1]

4

In [60]:
a[0][1][1]

4

In [61]:
a=np.array([[[2,4],[4,6]],[[1,3],[5,7]]])
a

array([[[2, 4],
        [4, 6]],

       [[1, 3],
        [5, 7]]])

In [62]:
a[1][1][0]

5

In [63]:
a[1,1,0]

5

In [64]:
a[-1,-1,-2]

5

In [65]:
a[0]

array([[2, 4],
       [4, 6]])

In [66]:
a[0,0]

array([2, 4])

In [67]:
## slicing retrive collections of values

In [68]:
a=np.array([1,2,3,4,5,6,7,8])

In [69]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [78]:
a[1:4]

[3, 4, 5]

In [71]:
a[0:5:2]

array([1, 3, 5])

In [75]:
a[:]

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [76]:
a[1::2]

[3, 5, 7, 9, 11]

In [77]:
a[:3]

[2, 3, 4]

In [79]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [82]:
a[0:1,1:4]

array([[2, 3, 4]])

In [83]:
a[0:,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [84]:
a[0:1,1:4]

array([[2, 3, 4]])

In [85]:
a[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [86]:
a[0:2,1:2]

array([[2],
       [7]])

In [87]:
a[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [88]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [89]:
a[1:,1:]

array([[ 7,  8,  9, 10]])

In [90]:
a[::,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10]])

In [93]:
a=np.array([[[1,2,3,4],[5,6,7,8],[21,22,23,24]],[[9,10,11,12],[13,14,15,16],[25,26,27,28]]])
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [21, 22, 23, 24]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [25, 26, 27, 28]]])

In [94]:
a[:,:,:1]

array([[[ 1],
        [ 5],
        [21]],

       [[ 9],
        [13],
        [25]]])

In [95]:
a[:,1:,::2]

array([[[ 5,  7],
        [21, 23]],

       [[13, 15],
        [25, 27]]])

In [96]:
## advanced indexing

In [ ]:
# integer indexing

In [97]:
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
index=np.array([1,3,6])
a[index]

array([2, 4, 7])

In [104]:
a[[1,3,6]]

array([2, 4, 7])

In [105]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
a[[0,2],[2,0]]

array([3, 7])

In [107]:
a[[1,1,2],[0,2,1]]

array([4, 6, 8])

In [111]:
# boolean indexing

In [113]:
a=np.array([[1,-2,3,4],[-1,4,-2,9]])

In [114]:
a

array([[ 1, -2,  3,  4],
       [-1,  4, -2,  9]])

In [115]:
a[a<0]

array([-2, -1, -2])

In [116]:
a[a>0]

array([1, 3, 4, 4, 9])

In [117]:
a[a<0]*2

array([-4, -2, -4])

In [118]:
a[a>4]

array([9])

In [119]:
## arithmatic operation

In [120]:
# using scalars( constant value)

In [121]:
a=np.array([1,2,3,4,5])

In [122]:
a

array([1, 2, 3, 4, 5])

In [123]:
a+2

array([3, 4, 5, 6, 7])

In [124]:
a-1

array([0, 1, 2, 3, 4])

In [125]:
a*3

array([ 3,  6,  9, 12, 15])

In [126]:
a/10

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [128]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [129]:
a%2

array([1, 0, 1, 0, 1], dtype=int32)

In [130]:
a=np.array([[2,3],[4,5]])
a

array([[2, 3],
       [4, 5]])

In [131]:
a+2

array([[4, 5],
       [6, 7]])

In [132]:
a-2

array([[0, 1],
       [2, 3]])

In [133]:
#by using array

In [134]:
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])

In [135]:
a+b

array([ 4,  6,  8, 10])

In [136]:
a-b

array([-2, -2, -2, -2])

In [137]:
a*b

array([ 3,  8, 15, 24])

In [138]:
a/b

array([0.33333333, 0.5       , 0.6       , 0.66666667])

In [139]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,4,6],[1,3,5]])

In [140]:
a+b

array([[ 3,  6,  9],
       [ 5,  8, 11]])

In [141]:
a-b

array([[-1, -2, -3],
       [ 3,  2,  1]])

In [142]:
a%b

array([[1, 2, 3],
       [0, 2, 1]], dtype=int32)

In [143]:
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])

In [144]:
np.add(a,b)

array([ 4,  6,  8, 10])

In [145]:
np.subtract(a,b)

array([-2, -2, -2, -2])

In [146]:
np.multiply(a,b)

array([ 3,  8, 15, 24])

In [147]:
np.divide(a,b)

array([0.33333333, 0.5       , 0.6       , 0.66666667])

In [148]:
np.mod(a,b)

array([1, 2, 3, 4], dtype=int32)

In [149]:
np.power(a,b)

array([   1,   16,  243, 4096], dtype=int32)

In [150]:
## broadcasting-- perform arithmatic operation of different size or shape

In [151]:
a=np.array([1,2,3])
b=np.array([2,3,4,5])

In [152]:
a.shape

(3,)

In [153]:
b.shape

(4,)

In [154]:
a+b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [155]:
## bradcasting rule
#1 size of each dimention are same
#2 size of one array is 1

In [156]:
a

array([1, 2, 3])

In [158]:
b=np.array([[1,2,3],[2,3,4]])
b

array([[1, 2, 3],
       [2, 3, 4]])

In [159]:
a+b

array([[2, 4, 6],
       [3, 5, 7]])

In [160]:
a=np.array([[1,2,3],[2,3,4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [165]:
a.ndim

2

In [163]:
a.shape

(2, 3)

In [161]:
b=np.array([1,2,3])
b

array([1, 2, 3])

In [166]:
b.ndim

1

In [164]:
b.shape

(3,)

In [162]:
a+b

array([[2, 4, 6],
       [3, 5, 7]])

In [167]:
## Manupilation of array

In [168]:
#reshape
#resize

In [170]:
#np.rehape(array, shape, order)
# order c=row, f=column

In [173]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [174]:
a.shape

(10,)

In [178]:
a.size

10

In [176]:
b=np.reshape(a, (5,2))
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [177]:
b=np.reshape(a, (5,2), order='F')
b

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [179]:
b.shape

(5, 2)

In [180]:
b.size

10

In [181]:
a.reshape((2,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [182]:
a.reshape((2,5), order='F')

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [183]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [185]:
#np.resize(array, shape)

In [186]:
np.resize(a,(2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [187]:
np.resize(a,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  1,  2]])

In [189]:
np.resize(a,(5,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  1,  2],
       [ 3,  4,  5]])

In [190]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

In [191]:
help(np.resize)

Help on function resize in module numpy:

resize(a, new_shape)
    Return a new array with the specified shape.
    
    If the new array is larger than the original array, then the new
    array is filled with repeated copies of `a`.  Note that this behavior
    is different from a.resize(new_shape) which fills with zeros instead
    of repeated copies of `a`.
    
    Parameters
    ----------
    a : array_like
        Array to be resized.
    
    new_shape : int or tuple of int
        Shape of resized array.
    
    Returns
    -------
    reshaped_array : ndarray
        The new array is formed from the data in the old array, repeated
        if necessary to fill out the required number of elements.  The
        data are repeated in the order that they are stored in memory.
    
    See Also
    --------
    np.reshape : Reshape an array without changing the total size.
    np.pad : Enlarge and pad an array.
    np.repeat: Repeat elements of an array.
    ndarray.resize : resiz

In [192]:
##flatening array
# using flatten()- convert ND array to 1D araay
#ravel()

In [193]:
#ndarray.flatten(order)

In [196]:
a=np.array([[[1,2],[2,3]],[[2,4],[6,7]]])
a

array([[[1, 2],
        [2, 3]],

       [[2, 4],
        [6, 7]]])

In [197]:
a.flatten()

array([1, 2, 2, 3, 2, 4, 6, 7])

In [198]:
a.flatten(order='F')

array([1, 2, 2, 6, 2, 4, 3, 7])

In [199]:
a.flatten(order='A')

array([1, 2, 2, 3, 2, 4, 6, 7])

In [200]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [201]:
a.flatten()

array([1, 2, 3, 4])

In [202]:
a.flatten(order='F')

array([1, 3, 2, 4])

In [203]:
#np.ravel(array, order)

In [204]:
a

array([[1, 2],
       [3, 4]])

In [205]:
np.ravel(a)

array([1, 2, 3, 4])

In [206]:
np.ravel(a,order='F')

array([1, 3, 2, 4])

In [207]:
a=np.array([[[1,2],[2,3]],[[2,4],[6,7]]])
a

array([[[1, 2],
        [2, 3]],

       [[2, 4],
        [6, 7]]])

In [208]:
np.ravel(a,order='F')

array([1, 2, 2, 6, 2, 4, 3, 7])

In [209]:
a.ravel()

array([1, 2, 2, 3, 2, 4, 6, 7])

In [2]:
## transpose()

In [3]:
#np.transpose(array, axes=None)

In [16]:
a=np.arange(1,11).reshape(5,2)

In [7]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [8]:
np.transpose(a)

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [9]:
np.transpose(a).shape

(2, 5)

In [17]:
np.transpose(a, axes=(1,0))

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [18]:
np.transpose(a, axes=(0,1))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [19]:
a=np.arange(1,25).reshape(2,3,4)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [20]:
np.transpose(a)

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [12]:
np.transpose(a).shape

(4, 3, 2)

In [21]:
np.transpose(a, axes=(1,2,0))

array([[[ 1, 13],
        [ 2, 14],
        [ 3, 15],
        [ 4, 16]],

       [[ 5, 17],
        [ 6, 18],
        [ 7, 19],
        [ 8, 20]],

       [[ 9, 21],
        [10, 22],
        [11, 23],
        [12, 24]]])

In [22]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.transpose(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a.transpose()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a.T

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
## swapexws()-- interchange 2 dimentions or axes

In [27]:
#np.swapaxes(array, axis1, axis2)

In [29]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [30]:
np.swapaxes(a, 1, 0)

array([[1, 3],
       [2, 4]])

In [31]:
np.swapaxes(a, 0, 1)

array([[1, 3],
       [2, 4]])

In [32]:
a=np.array([[1,2,3,4]])
a

array([[1, 2, 3, 4]])

In [33]:
np.swapaxes(a, 0, 1)

array([[1],
       [2],
       [3],
       [4]])

In [34]:
np.swapaxes(a, 1, 0)

array([[1],
       [2],
       [3],
       [4]])

In [35]:
a=np.arange(1,25).reshape(2,3,4)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [37]:
np.swapaxes(a, 1, 2)

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])

In [38]:
np.swapaxes(a, 2, 1)

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])

In [40]:
a.swapaxes(1,2)

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])

In [41]:
## joining 2 or more nmpy array

In [42]:
# np.concatenate(arrays, axis=0, out=None)
# dimesions, out is destination for saving result
# other axes except the concatenation axes should be same

In [43]:
a=np.arange(1,5)
b=np.arange(6)

In [44]:
a

array([1, 2, 3, 4])

In [45]:
b

array([0, 1, 2, 3, 4, 5])

In [46]:
np.concatenate((a,b))

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 5])

In [47]:
c=np.arange(4)
c

array([0, 1, 2, 3])

In [48]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3])

In [53]:
d=np.zeros(14)

In [54]:
np.concatenate((a,b,c), out=d)

array([1., 2., 3., 4., 0., 1., 2., 3., 4., 5., 0., 1., 2., 3.])

In [55]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])

In [58]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
np.concatenate((a,b), axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [60]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [62]:
## vstack()

In [63]:
#np.vstack((arrays))

In [67]:
a=np.arange(6)
b=np.arange(5)
c=np.arange(6)

In [68]:
np.vstack((a,b,c))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 6 and the array at index 1 has size 5

In [69]:
np.vstack((a,c))

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [70]:
np.vstack((a,c)).ndim

2

In [72]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [73]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [74]:
# hstack

In [75]:
# numpy.hstack((arrays)

In [76]:
a=np.arange(6)
b=np.arange(5)
c=np.arange(6)

In [78]:
np.hstack((b,c))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5])

In [79]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [80]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [81]:
np.hstack((a,b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [82]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [83]:
##split()

In [84]:
# np.split(array, section=, axis=0)

In [86]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.split(a,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [88]:
a=np.arange(1,13).reshape(6,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [89]:
np.split(a,2)

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

In [91]:
# hsplit
# np.hsplit(array, section, axis=1)
# np.vsplit(array, section, axis=0)

In [92]:
a=np.arange(1,13).reshape(6,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [93]:
np.vsplit(a,2)

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

In [94]:
np.hsplit(a,2)

[array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12]])]

In [95]:
## insert and delete an element

In [96]:
# np.insert(array, object or index, values, axis=None)

In [97]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
np.insert(a, 1, 50)

array([ 1, 50,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
np.insert(a, 1, 50.12)

array([ 1, 50,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
np.insert(a, (1,3), 50)

array([ 1, 50,  2,  3, 50,  4,  5,  6,  7,  8,  9, 10])

In [101]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [102]:
np.insert(a, 1, 23)

array([ 1, 23,  2,  3,  4])

In [103]:
np.insert(a, 1, 23, axis=0)

array([[ 1,  2],
       [23, 23],
       [ 3,  4]])

In [104]:
np.insert(a, 1, 23, axis=1)

array([[ 1, 23,  2],
       [ 3, 23,  4]])

In [105]:
np.insert(a, 1, [1,2], axis=0)

array([[1, 2],
       [1, 2],
       [3, 4]])

In [106]:
np.insert(a, 1, [1,2,3], axis=0)

ValueError: could not broadcast input array from shape (1,3) into shape (1,2)

In [108]:
## append()
#np.append(array, value, axis=None)

In [109]:
a=np.arange(1,14)

In [110]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [111]:
np.append(a, 30)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 30])

In [112]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [113]:
np.append(a, [[5,6]])

array([1, 2, 3, 4, 5, 6])

In [114]:
np.append(a, [[5,6]], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [115]:
np.append(a, [[5,6]], axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [116]:
np.append(a, [[5],[6]], axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [117]:
## delete()
#np.delete(array, object or index, axis=None)

In [118]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
np.delete(a, 3)

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])

In [121]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [122]:
np.delete(a, 3)

array([1, 2, 3])

In [124]:
np.delete(a, 1, axis=0)

array([[1, 2]])

In [127]:
np.delete(a, 0, axis=1)

array([[2],
       [4]])

In [128]:
## matrix

In [130]:
a=np.array([[10,20],[30,40]])
b=np.array([[1,2],[3,4]])

In [131]:
a

array([[10, 20],
       [30, 40]])

In [132]:
b

array([[1, 2],
       [3, 4]])

In [133]:
a*b

array([[ 10,  40],
       [ 90, 160]])

In [134]:
np.dot(a,b)

array([[ 70, 100],
       [150, 220]])

In [142]:
c=np.zeros((2,2), dtype=int)
c

array([[0, 0],
       [0, 0]])

In [143]:
np.dot(a,b, out=c)

array([[ 70, 100],
       [150, 220]])

In [145]:
## np.matrix(data, dtype=, copy=True)
## matrix cannot be 1d or 3d or above

In [146]:
a=np.matrix("1 2;3 4")
a

matrix([[1, 2],
        [3, 4]])

In [148]:
b=np.matrix([[10,20],[30,40]])
b

matrix([[10, 20],
        [30, 40]])

In [149]:
a*b

matrix([[ 70, 100],
        [150, 220]])

In [150]:
## inverse of matrix
## np.linalg --- linear algebra

In [151]:
##np.linalg.inv(a)

In [152]:
a=np.matrix([[1,2],[3,4]])
a

matrix([[1, 2],
        [3, 4]])

In [153]:
b=np.linalg.inv(a)
b

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [2]:
## power of matrix

In [3]:
#np.linalg.matrix_power(array,n)
# matrix should be square
# n-power
# n can be zero + or -
#n=-ve first it will calculate inverse then calculate power of +ve n

In [4]:
a=np.matrix([[1,2],[3,4]])
a

matrix([[1, 2],
        [3, 4]])

In [5]:
np.linalg.matrix_power(a, 2)

matrix([[ 7, 10],
        [15, 22]])

In [6]:
np.dot(a,a)

matrix([[ 7, 10],
        [15, 22]])

In [7]:
np.linalg.matrix_power(a, 3)

matrix([[ 37,  54],
        [ 81, 118]])

In [8]:
np.linalg.matrix_power(a, 0)

matrix([[1, 0],
        [0, 1]])

In [9]:
np.linalg.matrix_power(a, -2)

matrix([[ 5.5 , -2.5 ],
        [-3.75,  1.75]])

In [10]:
b=np.linalg.inv(a)

In [11]:
b

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [12]:
np.linalg.matrix_power(b, 2)

matrix([[ 5.5 , -2.5 ],
        [-3.75,  1.75]])

In [13]:
## linear equation

In [14]:
# np.linalg.solve(a,b)

In [ ]:
# 3x+y=9
# x+2y=8

In [18]:
a=np.array([[3,1],[1,2]])
a

array([[3, 1],
       [1, 2]])

In [19]:
b=np.array([9,8])
b

array([9, 8])

In [20]:
np.linalg.solve(a,b)

array([2., 3.])

In [ ]:
# 6x+2y-5z=13
# 3x+3y-2z=13
# 7x+5y-3z=26

In [21]:
a=np.array([[6,2,-5],[3,3,-2],[7,5,-3]])
a

array([[ 6,  2, -5],
       [ 3,  3, -2],
       [ 7,  5, -3]])

In [22]:
b=np.array([13,13,26])
b

array([13, 13, 26])

In [24]:
np.linalg.solve(a,b)

array([2., 3., 1.])

In [25]:
## determinant of matrix

In [ ]:
#np.linalg.det(a)

In [26]:
a=np.matrix([[1,2],[3,4]])
a

matrix([[1, 2],
        [3, 4]])

In [28]:
np.linalg.det(a)

-2.0000000000000004

In [29]:
round(np.linalg.det(a))

-2

In [31]:
b=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
b

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [32]:
np.linalg.det(b)

6.66133814775094e-16

In [33]:
round(np.linalg.det(b))

0